# -*- coding: utf-8 -*-
"""module02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x5D8BWa1XRx1AZVbld2UUH-Jgt0M1bc7
"""

# module02.py
def sum(a, b):
    return a + b

def multi(a, b):
    return a * b

def sub(a, b):
    return a - b

print('Module 02 run')
ret=sum(10,30)
print(ret)