# -*- coding: utf-8 -*-
"""module03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-m_FJrN1dzhGhZC1bIq8_ryLpXLQdW6
"""

#module03.py
PI=3.14
def viewPI():
  print(PI)

if __name__=="__main__":
  print('Module 03 run')