# -*- coding: utf-8 -*-
"""module01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTO8Edrvmi6WjcdwqOe3thVwjAlaoZrg
"""

# module01.py
def sum(a, b):
    return a + b