# -*- coding: utf-8 -*-
"""module03_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11S2O1aJL2N-sc0ZPEmyLN1kNcDDrIDF8
"""

#module03_1.py
PI=3.14
def viewPI():
  print(PI)

def trnsAngle():
  return (PI*angle)

if __name__=="__main__":
  print('Module 03 run')

