# -*- coding: utf-8 -*-
"""module04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEV6FiaJBvQfwoduSJc24cS4XHKDdt0E
"""

code=0
def getCode():
  return code #code변수의 값을 반환한다.
def setCode(arg):
  code=arg    #code변수에 arg를 대입한다.