# -*- coding: utf-8 -*-
"""module04_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIrqFrwtssd3yVf_XKmqfCHUTWpz8M3F
"""

#module04_1.py
code=0
def getCode():
  return code #code변수의 값을 반환한다.
def setCode(arg):
  global code #code변수를 전역변수로 선언한다.
  code=arg    #code변수에 arg를 대입한다.