# -*- coding: utf-8 -*-
"""module02_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAkPcPodDXn4bzlVBFDGadiEiNS_qveK
"""

# module02_1.py
def sum(a, b):
    return a + b

def multi(a, b):
    return a * b

def sub(a, b):
    return a - b

#if와 __name__ 사이에 공백
if __name__ == "__main__":
  print('Module 02 run')
  ret=sum(10,30)
  print(ret)