# -*- coding: utf-8 -*-
"""module01_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpQxYPxahFxdLxnhGng1e_48QXm-Kkfs
"""

# module01_1.py
def sum(a, b):
    return a + b

def multi(a, b):
    return a * b

def sub(a, b):
    return a - b