# -*- coding: utf-8 -*-
"""classes05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19b5t3Ytj9BkGdrA3Ptd9ACjztO1F8ZT9
"""

#classes05.py
class Pokemon:
  id="unknown"

  # 인스턴스 변수#name을 정하지 않으면 생성불가
  def __init__(self,arg):
    self.name=arg

  def sleep(self):#매서드 정의 시 반드시 self를 적어야 한다.
    print(self.name,"Zzzzzzz....")

class BattlePokemon(Pokemon):
  def attack(self):
    print(self.name,"attack")
  def defense(self):
    print(self.name,"defense")
  pass