# -*- coding: utf-8 -*-
"""classes03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_Ay04m3ivPUQPy-F0FoB0jKpTN7VA4x
"""

#classes03.py
class Pokemon:
  id="unknown"

  # 인스턴스 변수#name을 정하지 않으면 생성불가
  def __init__(self,arg):
    self.name=arg

  def sleep(self):#매서드 정의 시 반드시 self를 적어야 한다.
    print(self.name,"Zzzzzzz....")

  pass