# -*- coding: utf-8 -*-
"""classes01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EeXtYopEFSem73bS8jq3wVVjcFU6QQVn
"""

#classes01.py
class Pokemon:
  id="unknown"