# -*- coding: utf-8 -*-
"""classes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120GGD5S8bNUnMaCV0v0fZy1HP8XkQL0j
"""

#classes.py
class Pokemon:
  pass