# -*- coding: utf-8 -*-
"""classes02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdgqgFH22iHV-y3DZYbR6-2RvKufE1Kj
"""

#classes02.py
class Pokemon:
  id="unknown"
  def sleep(self):#매서드 정의 시 반드시 self를 적어야 한다.
    print(self.name,"Zzzzzzz....")
  pass

