# -*- coding: utf-8 -*-
"""module05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_VCoOFYplw6wjl7AOUvOGUpPG9ixHrx5
"""

def total(scores):
  ret=0
  for v in scores:
    ret+=v
  return ret

def average(scores):
  sum=total(scores)
  return (sum//len(scores))